"""Response formatting node - prepares final output for user."""

from ..state import AgentState


async def format_response_node(state: AgentState) -> dict:
    """
    Format the final response to present to the user.

    This node combines all the results and explanation trace
    into a well-formatted response.
    """
    # Check if we already have a final response (from clarify or schema nodes)
    if state.get("final_response"):
        return {}  # Already formatted

    intent = state.get("intent")
    explanation_trace = state.get("explanation_trace", [])
    error = state.get("error")

    # Handle errors
    if error:
        response = _format_error(error, explanation_trace)
        return {"final_response": response}

    # Handle SQL generation result
    generated_sql = state.get("generated_sql")
    if generated_sql:
        response = _format_sql_response(state, generated_sql, explanation_trace)
        return {"final_response": response}

    # Fallback
    response = _format_fallback(state, explanation_trace)
    return {"final_response": response}


def _format_sql_response(state: dict, sql: str, trace: list) -> str:
    """Format SQL generation response with full explainability."""
    field_selection = state.get("field_selection", {})
    current_query = state.get("current_query", "")

    lines = [
        "✅ **SQL GENERATED**",
        "",
        "═" * 50,
        "📋 **YOUR QUESTION:**",
        f"  \"{current_query}\"",
        "",
        "🎯 **FIELD MAPPING:**",
    ]

    # Show field mapping from explanation trace
    for item in trace:
        if "→" in item:
            lines.append(f"  {item.strip()}")

    lines.extend([
        "",
        "📊 **QUERY STRUCTURE:**",
        f"  • Model: {field_selection.get('model', 'N/A')}",
        f"  • Explore: {field_selection.get('explore', 'N/A')}",
        f"  • Dimensions: {field_selection.get('dimensions', [])}",
        f"  • Measures: {field_selection.get('measures', [])}",
    ])

    filters = field_selection.get("filters", {})
    if filters:
        lines.append(f"  • Filters: {filters}")

    lines.extend([
        "",
        "═" * 50,
        "💾 **GENERATED SQL:**",
        "",
        "```sql",
        sql,
        "```",
        "",
        "═" * 50,
        "",
        "💡 This SQL was generated by Looker's semantic layer.",
        "   Copy and run it in your preferred query tool.",
    ])

    return "\n".join(lines)


def _format_error(error: str, trace: list) -> str:
    """Format error response."""
    lines = [
        "❌ **ERROR**",
        "",
        f"  {error}",
        "",
    ]

    if trace:
        lines.append("📜 **What happened:**")
        for item in trace[-5:]:  # Last 5 trace items
            lines.append(f"  {item}")

    lines.extend([
        "",
        "💡 **Try:**",
        "  • Rephrasing your question",
        "  • Asking \"What data is available?\"",
        "  • Being more specific about what you're looking for",
    ])

    return "\n".join(lines)


def _format_fallback(state: dict, trace: list) -> str:
    """Format fallback response when nothing specific to show."""
    intent = state.get("intent", "unknown")
    current_query = state.get("current_query", "")

    lines = [
        "🤔 **I processed your request but don't have a specific output.**",
        "",
        f"  Intent: {intent}",
        f"  Query: \"{current_query}\"",
        "",
    ]

    if trace:
        lines.append("📜 **Processing trace:**")
        for item in trace:
            lines.append(f"  {item}")

    lines.extend([
        "",
        "💡 **Try asking:**",
        "  • \"What data is available?\" - see schema",
        "  • \"Show me sales by region\" - generate SQL",
        "  • \"What is total_revenue?\" - explain a field",
    ])

    return "\n".join(lines)
