"""Prompt templates for the Semantic Layer Agent."""

from .classifier import INTENT_CLASSIFICATION_PROMPT
from .selector import MODEL_SELECTION_PROMPT, FIELD_SELECTION_PROMPT
from .explainer import FIELD_EXPLANATION_PROMPT, SCHEMA_OVERVIEW_PROMPT

__all__ = [
    "INTENT_CLASSIFICATION_PROMPT",
    "MODEL_SELECTION_PROMPT",
    "FIELD_SELECTION_PROMPT",
    "FIELD_EXPLANATION_PROMPT",
    "SCHEMA_OVERVIEW_PROMPT",
]
